### ISSUE TITLE
Bug - STYRBAR buttons mallfuntion

### ISSUE THREAD

**Issue by Sakriel** [lsismeiro/awesome-ha-blueprints#11]
### Blueprint name

Controller

### Home Assistant Core Version

2024.3.0

### Home Assistant Installation Type

Home Assistant Supervised

### Description

I got 2 problems with styrbar buttons.

1. When i want to increase brightness with long up press it first goes to max brightness and than goes back to the current state value and goes up correctly. It does not happen with lower down the brightness with bottom button.

I will provide z2mqtt logs regarding that action (long up press)

`Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":"brightness_move_up","action_rate":83,"battery":85,"brightness":215,"linkquality":81,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":"","battery":85,"brightness":215,"linkquality":81,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Multiwłącznik/action', payload 'brightness_move_up'
Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"**brightness":254**,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"**brightness":98**,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"**brightness":123**,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:22MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":null,"action_brightness_delta":20,"battery":85,"brightness":235,"linkquality":81,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"brightness":147,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":null,"action_brightness_delta":20,"battery":85,"brightness":255,"linkquality":81,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"brightness":172,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"brightness":197,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":123,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":"brightness_stop","battery":85,"brightness":255,"linkquality":78,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":"","battery":85,"brightness":255,"linkquality":78,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Multiwłącznik/action', payload 'brightness_stop'
Info 2024-03-12 23:34:23MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"brightness":222,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'`

2. Double tap doesnt work at all. 

This is the log from z2mqtt:

`Info 2024-03-12 23:39:56MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{"action":"on","battery":85,"brightness":255,"linkquality":75,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:39:56MQTT publish: topic 'zigbee2mqtt/Multiwłącznik', payload '{**"action":""**,"battery":85,"brightness":255,"linkquality":75,"update":{"installed_version":65572,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:39:56MQTT publish: topic 'zigbee2mqtt/Multiwłącznik/action', payload 'on'
Info 2024-03-12 23:39:56MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"brightness":76,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Info 2024-03-12 23:39:56MQTT publish: topic 'zigbee2mqtt/Żarówka', payload '{"brightness":76,"color":{"h":27,"hue":27,"s":92,"saturation":92,"x":0.5056,"y":0.4152},"color_mode":"xy","color_options":{"execute_if_off":false},"color_temp":454,"color_temp_startup":454,"level_config":{"on_level":"previous"},"linkquality":126,"power_on_behavior":"on","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'`

It seems that double button is not being read by HA. It reads single up push and than empty action and it looks like it is ignoring second click.

Can i please ask for a fix?

### Automation YAML config

```yaml
ikea_e2001_e2002.yaml
```

### To Reproduce

1. try to brighten up using long press
2. try to execute double action

### Expected behavior

1. brighten up with long press smoothly lifts the brightness parameter
2. double click is visible in z2mqtt logs and executes action

### Actual Behaviour

1. When i want to increase brightness with long up press it first goes to max brightness and than goes back to the current state value and goes up correctly. It does not happen with lower down the brightness with bottom button.
2. Double click work exactly as single click

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by LewisSpring** [comment]
Hiya, sorry to hear you're having issues.

Can you confirm that you're using the latest version of the blueprint?

**Comment by Sakriel** [comment]
@LewisSpring - yes - i can confirm - downloaded it yesterday.

**Comment by LewisSpring** [comment]
I have switched back to ZHA so cannot confirm any issues with Z2M rightr now.

I will create a test environment as soon as possible.

**Comment by LewisSpring** [comment]
I have not been able to get a test setup working, sorry.

Regarding the brightness, are you using the light hook?
Can you test if light brightness up actions in a normal automation cause the same issue? It could be that it's an issue with how the bulb reacts?

Regarding the double press, you may want to adjust the delay in the automation settings. The double press is a lot slower than most people expect and I want to make sure it's not that 👍

**Comment by Sakriel** [comment]
@LewisSpring - thanks for your prompt reply.

Brightness is fixed. When i did pair bulb again it started to work properly.

Double click button is still not working.

**Comment by LewisSpring** [comment]
Hi, thanks for troubleshooting. 

Please can you send a copy of the automation please?

Also, can you send logs with just the double press action in if possible?

Thanks

**Comment by drublin** [comment]
> @LewisSpring - thanks for your prompt reply.
> 
> Brightness is fixed. When i did pair bulb again it started to work properly.
> 
> Double click button is still not working.

@Sakriel , my double press works in this blueprint. 
- did you enable the switches "(Optional) Expose up button double press event" ?
- i increased the "(Optional) Helper - Double Press delay" to 900ms. (but it works also with default 500ms).
- a usual fast "mouse-like" double click does not work on my remote neither. Try slower clicks, with a pause in between.

I also check the automation text helper on the dashboard. It quickly shows the automation point of view on the clicks.
![image](https://github.com/lsismeiro/awesome-ha-blueprints/assets/102928430/aa0edb9f-e8aa-46cf-a5ed-46796e895687)

**Comment by LewisSpring** [comment]
Cheers @drublin, this is everything I would have said!
@Sakriel Please let us know if you are still having issues

**Comment by LewisSpring** [comment]
Hi @Sakriel 
As we've not heard from you, I am going to close this issue for now.
If you're still having issues please give us a shout and we can re-open and look into this for you.
