### ISSUE TITLE
When will be the E1524 fix merged to main?

### ISSUE THREAD

**Issue by jtulak** [lsismeiro/awesome-ha-blueprints#6]
### Blueprint name

ikea_e1524_e1810.yaml

### Description

The IKEA E1524 controller had some buttons renamed. There is already a branch with a fix in this repository, so I imported that blueprint and it works. But once it gets merged to main, I will have to re-do all the usages of this blueprint. What is the expected time for merging it?

Also thank you for keeping this alive. :)

**Comment by LewisSpring** [comment]
Hello. 

I've been quite busy recently, this just fell under my radar. 

I don't remember if anyone else confirmed the fix, as I can't check right now, but i will take your issue as confirmation of repair. 

I will create the pull request as soon as possible and merge. 

If you are using blueprints from this repository already, all you need to do is select the blueprint and press refresh (or similar process). 

If not, all you need to do is import the new blueprint and find-replace the EPMatt with lsismeiro. 

Cheers
